swagger: "2.0"
info:
  title: "API Documentation"
  version: "1.0"
  description: "API Documentation For AGROLYN Apps."

tags:
  - name: "authentication"
    description: "Endpoints related to authentication and authorization"
  - name: "article"
    description: "Endpoints related to articles"
  - name: "recipe"
    description: "Endpoints related to recipes"
  - name: "profile"
    description: "Endpoints related to user profile"
  - name: "question"
    description: "Endpoints related to question"

paths:
  /refresh-token:
    post:
      tags:
        - "authentication"
      summary: "Obtain a new access token using refresh token"
      description: "Use this endpoint to get a new access token without logging in again. Requires a valid refresh token in the Authorization header."
      parameters:
        - in: header
          name: Authorization
          required: true
          description: "Bearer token format with the refresh token (e.g., 'Bearer <refresh_token>')"
          schema:
            type: string
      responses:
        200:
          description: "Successfully obtained new access token"
          schema:
            type: object
            properties:
              access_token:
                type: string
                description: "New JWT access token for authenticated requests"
        401:
          description: "Invalid or expired refresh token"
        422:
          description: "Missing or invalid Authorization header format"

  /register:
    post:
      tags:
        - "authentication"
      summary: "Register a new user"
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              email:
                type: string
              address:
                type: string
              phone_number:
                type: string
              password:
                type: string
              roles_id:
                type: integer
      responses:
        201:
          description: "User registered successfully. Check email to confirm account."
        400:
          description: "Email already exists"

  /confirm/{token}:
    get:
      tags:
        - "authentication"
      summary: "Confirm user's email"
      parameters:
        - name: token
          in: path
          required: true
          type: string
          description: "The confirmation token sent via email"
      responses:
        200:
          description: "Email verified successfully"
        400:
          description: "Invalid or expired confirmation link"

  /login:
    post:
      tags:
        - "authentication"
      summary: "Login user and obtain JWT tokens (access and refresh)"
      consumes:
        - application/json
      parameters:
        - in: body
          name: credentials
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
                description: "User's email address"
              password:
                type: string
                description: "User's password"
      responses:
        200:
          description: "Logged in successfully with access and refresh tokens provided"
          schema:
            type: object
            properties:
              access_token:
                type: string
                description: "JWT access token for authenticated requests"
              refresh_token:
                type: string
                description: "JWT refresh token for obtaining new access tokens"
              id:
                type: integer
                description: "User's unique ID"
              email:
                type: string
                description: "User's email address"
              name:
                type: string
                description: "User's name"
              address:
                type: string
                description: "User's address"
              phone_number:
                type: string
                description: "User's phone number"
              img_profile:
                type: string
                description: "URL to user's profile image"
              roles_id:
                type: integer
                description: "User's role ID"
        401:
          description: "Invalid credentials"
        403:
          description: "Email not verified"

  /forgot_password:
    post:
      tags:
        - "authentication"
      summary: "Request password reset link"
      consumes:
        - application/json
      parameters:
        - in: body
          name: email
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
      responses:
        200:
          description: "Password reset email sent"
        404:
          description: "Email not found"

  /reset_password/{token}:
    get:
      tags:
        - "authentication"
      summary: "Confirm user's email reset password"
      parameters:
        - name: token
          in: path
          required: true
          type: string
          description: "The confirmation token reset password sent via email"
      responses:
        200:
          description: "Email reset password verified successfully"
        400:
          description: "Invalid or expired confirmation link"
    post:
      tags:
        - "authentication"
      summary: "Reset user password"
      consumes:
        - application/json
      parameters:
        - name: token
          in: path
          required: true
          type: string
          description: "The reset token sent via email"
        - in: body
          name: password
          required: true
          schema:
            type: object
            properties:
              new_password:
                type: string
      responses:
        200:
          description: "Password reset successfully"
        400:
          description: "Invalid or expired reset link"
        404:
          description: "User not found"

  /logout:
    post:
      tags:
        - "authentication"
      summary: "Logout user and invalidate session"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: "JWT token for authorization (e.g., 'Bearer <access_token>')"
      responses:
        200:
          description: "Logged out successfully"

  /articles/:
    get:
      tags:
        - "article"
      summary: "Get all articles"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: "JWT token for authorization (e.g., 'Bearer <access_token>')"
      responses:
        200:
          description: "A list of articles"
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  description: "The article ID"
                title:
                  type: string
                  description: "The title of the article"
                thumbnail:
                  type: string
                  description: "URL of the article thumbnail"
                description:
                  type: string
                  description: "A brief description of the article"
                location:
                  type: string
                  description: "The location related to the article"
                released_date:
                  type: string
                  format: date
                  description: "The release date of the article"

  /articles/{id}/:
    get:
      tags:
        - "article"
      summary: "Get article detail"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: "JWT token for authorization (e.g., 'Bearer <access_token>')"
        - name: id
          in: path
          required: true
          type: integer
          description: "The ID of the article to retrieve"
      responses:
        200:
          description: "Article details"
          schema:
            type: object
            properties:
              id:
                type: integer
                description: "The article ID"
              title:
                type: string
                description: "The title of the article"
              thumbnail:
                type: string
                description: "URL of the article thumbnail"
              description:
                type: string
                description: "A brief description of the article"
              location:
                type: string
                description: "The location related to the article"
              released_date:
                type: string
                format: date
                description: "The release date of the article"
        404:
          description: "Article not found"

  /recipes/:
    get:
      tags:
        - "recipe"
      summary: "Get all recipes"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: "JWT token for authorization (e.g., 'Bearer <access_token>')"
      responses:
        200:
          description: "A list of recipes"
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  description: "The recipe ID"
                title:
                  type: string
                  description: "The title of the recipe"
                img_recipe:
                  type: string
                  description: "URL of the recipe image"
                ingredients:
                  type: string
                  description: "The ingredients needed for the recipe"
                steps:
                  type: string
                  description: "The instructions for preparing the recipe"

  /recipes/{id}/:
    get:
      tags:
        - "recipe"
      summary: "Get recipe detail"
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: "JWT token for authorization (e.g., 'Bearer <access_token>')"
        - name: id
          in: path
          required: true
          type: integer
          description: "The ID of the recipe to retrieve"
      responses:
        200:
          description: "Recipe details"
          schema:
            type: object
            properties:
              id:
                type: integer
                description: "The recipe ID"
              title:
                type: string
                description: "The title of the recipe"
              img_recipe:
                type: string
                description: "URL of the recipe image"
              ingredients:
                type: string
                description: "The ingredients needed for the recipe"
              steps:
                type: string
                description: "The instructions for preparing the recipe"
        404:
          description: "Recipe not found"
  /edit-profile:
    put:
      tags:
        - "profile"
      summary: "Edit user profile"
      description: "Endpoint for updating user's profile information."
      consumes:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: "JWT token for authorization (e.g., 'Bearer <access_token>')"
        - in: body
          name: profile
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                description: "User's updated name"
              address:
                type: string
                description: "User's updated address"
              phone_number:
                type: string
                description: "User's updated phone number"
      responses:
        200:
          description: "Profile updated successfully"
        400:
          description: "No valid fields to update"
        404:
          description: "User not found"
        401:
          description: "Unauthorized access"

      paths:
  /questions:
    get:
      tags:
        - "question"
      summary: "Get all questions"
      description: "Retrieve a list of all questions."
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: "JWT token for authorization (e.g., 'Bearer <access_token>')"
      responses:
        200:
          description: "A list of questions"
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  description: "The question ID"
                question:
                  type: string
                  description: "The question content"
                like_num:
                  type: integer
                  description: "Number of likes on the question"
                users_id:
                  type: integer
                  description: "ID of the user who asked the question"
                plant_types_id:
                  type: integer
                  description: "ID of the plant type associated with the question"
                released_date:
                  type: string
                  format: date
                  description: "The date the question was released"
                img_q:
                  type: string
                  description: "URL of the image associated with the question"

  /questions/{id}:
    get:
      tags:
        - "question"
      summary: "Get question detail"
      description: "Retrieve details of a specific question by its ID."
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: "JWT token for authorization (e.g., 'Bearer <access_token>')"
        - name: id
          in: path
          required: true
          type: integer
          description: "The ID of the question to retrieve"
      responses:
        200:
          description: "Question details"
          schema:
            type: object
            properties:
              id:
                type: integer
                description: "The question ID"
              question:
                type: string
                description: "The question content"
              like_num:
                type: integer
                description: "Number of likes on the question"
              users_id:
                type: integer
                description: "ID of the user who asked the question"
              plant_types_id:
                type: integer
                description: "ID of the plant type associated with the question"
              released_date:
                type: string
                format: date
                description: "The date the question was released"
              img_q:
                type: string
                description: "URL of the image associated with the question"
        404:
          description: "Question not found"

    post:
      tags:
        - "question"
      summary: "Create a new question"
      description: "Add a new question to the system."
      consumes:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: "JWT token for authorization (e.g., 'Bearer <access_token>')"
        - in: body
          name: question
          required: true
          schema:
            type: object
            properties:
              question:
                type: string
                description: "The content of the question"
              users_id:
                type: integer
                description: "ID of the user asking the question"
              plant_types_id:
                type: integer
                description: "ID of the plant type associated with the question"
              img_q:
                type: string
                description: "URL of the image associated with the question"
      responses:
        201:
          description: "Question created successfully"
        400:
          description: "Invalid input data"

  /questions/{id}/like:
    put:
      tags:
        - "question"
      summary: "Like a question"
      description: "Increase the like count for a specific question."
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: "JWT token for authorization (e.g., 'Bearer <access_token>')"
        - name: id
          in: path
          required: true
          type: integer
          description: "The ID of the question to like"
      responses:
        200:
          description: "Like added successfully"
        404:
          description: "Question not found"
