swagger: "2.0"
info:
  title: "API Documentation"
  version: "1.0"
  description: "API Documentation For AGROLYN Apps."

paths:
  /articles/:
    get:
      summary: "Get all articles"
      responses:
        200:
          description: "A list of articles"
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  description: "The article ID"
                title:
                  type: string
                  description: "The title of the article"
                thumbnail:
                  type: string
                  description: "URL of the article thumbnail"
                description:
                  type: string
                  description: "A brief description of the article"
                location:
                  type: string
                  description: "The location related to the article"
                released_date:
                  type: string
                  format: date
                  description: "The release date of the article"

  /articles/{id}/:
    get:
      summary: "Get article detail"
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          description: "The ID of the article to retrieve"
      responses:
        200:
          description: "Article details"
          schema:
            type: object
            properties:
              id:
                type: integer
                description: "The article ID"
              title:
                type: string
                description: "The title of the article"
              thumbnail:
                type: string
                description: "URL of the article thumbnail"
              description:
                type: string
                description: "A brief description of the article"
              location:
                type: string
                description: "The location related to the article"
              released_date:
                type: string
                format: date
                description: "The release date of the article"
        404:
          description: "Article not found"

  /recipes/:
    get:
      summary: "Get all recipes"
      responses:
        200:
          description: "A list of recipes"
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  description: "The recipe ID"
                title:
                  type: string
                  description: "The title of the recipe"
                img_recipe:
                  type: string
                  description: "URL of the recipe image"
                ingredients:
                  type: string
                  description: "The ingredients needed for the recipe"
                steps:
                  type: string
                  description: "The instructions for preparing the recipe"

  /recipes/{id}/:
    get:
      summary: "Get recipe detail"
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          description: "The ID of the recipe to retrieve"
      responses:
        200:
          description: "Recipe details"
          schema:
            type: object
            properties:
              id:
                type: integer
                description: "The recipe ID"
              title:
                type: string
                description: "The title of the recipe"
              img_recipe:
                type: string
                description: "URL of the recipe image"
              ingredients:
                type: string
                description: "The ingredients needed for the recipe"
              steps:
                type: string
                description: "The instructions for preparing the recipe"
        404:
          description: "Recipe not found"
